#!/bin/bash

clear

echo "███████╗██╗  ██╗ █████╗ ██╗  ██╗"
echo "Shahadat Host Local Server"

echo ""
echo "1 Install Server"
echo "2 Start Server"
echo "3 Stop Server"
echo "4 Database Manager"

read option

if [ $option -eq 1 ]
then
bash install.sh
fi

if [ $option -eq 2 ]
then
bash start.sh
fi

if [ $option -eq 3 ]
then
bash stop.sh
fi

if [ $option -eq 4 ]
then
bash db.sh
fi